# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  app1:
    image: app1
    build:
      context: .
      dockerfile: App1/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5001:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    
  app2:
    image: app2
    build:
      context: .
      dockerfile: App2/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5002:5002
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
